

import 'package:flutter/material.dart';
import 'package:flutter_staggered_grid_view/flutter_staggered_grid_view.dart';

class NamesOfAllahPage extends StatelessWidget {
  final List<String> names = [
    "الرَّحْمَـٰنُ (Ar-Rahman)",
    "الرَّحِيمُ (Ar-Rahim)",
    "الْمَلِكُ (Al-Malik)",
    "الْقُدُّوسُ (Al-Quddus)",
    "السَّلاَمُ (As-Salam)",
    "الْمُؤْمِنُ (Al-Mu’min)",
    "الْمُهَيْمِنُ (Al-Muhaymin)",
    "الْعَزِيزُ (Al-Aziz)",
    "الْجَبَّارُ (Al-Jabbar)",
    "الْمُتَكَبِّرُ (Al-Mutakabbir)",
    "الْخَالِقُ (Al-Khaliq)",
    "الْبَارِئُ (Al-Bari)",
    "الْمُصَوِّرُ (Al-Musawwir)",
    "الْغَفَّارُ (Al-Ghaffar)",
    "الْقَهَّارُ (Al-Qahhar)",
    "الْوَهَّابُ (Al-Wahhab)",
    "الرَّزَّاقُ (Ar-Razzaq)",
    "الْفَتَّاحُ (Al-Fattah)",
    "العَلِيمُ (Al-Alim)",
    "الْقَابِضُ (Al-Qabid)",
    "الْبَاسِطُ (Al-Basit)",
    "الْخَافِضُ (Al-Khafid)",
    "الرَّافِعُ (Ar-Rafi)",
    "الْمُعِزُّ (Al-Mu'izz)",
    "المُذِلُّ (Al-Mudhill)",
    "السَّمِيعُ (As-Sami)",
    "الْبَصِيرُ (Al-Basir)",
    "الْحَكَمُ (Al-Hakam)",
    "الْعَدْلُ (Al-'Adl)",
    "اللَّطِيفُ (Al-Latif)",
    "الْخَبِيرُ (Al-Khabir)",
    "الْحَلِيمُ (Al-Halim)",
    "الْعَظِيمُ (Al-Azim)",
    "الْغَفُورُ (Al-Ghafur)",
    "الشَّكُورُ (Ash-Shakur)",
    "الْكَبِيرُ (Al-Kabir)",
    "الْحَفِيظُ (Al-Hafiz)",
    "الْمُكِيدُ (Al-Muqit)",
    "الْحسِيبُ (Al-Hasib)",
    "الْجَلِيلُ (Al-Jalil)",
    "الْكَرِيمُ (Al-Karim)",
    "الرَّقِيبُ (Ar-Raqib)",
    "الْمُجِيبُ (Al-Mujib)",
    "الْوَاسِعُ (Al-Wasi)",
    "الْحَكِيمُ (Al-Hakim)",
    "الْوَدُودُ (Al-Wadud)",
    "الْمَجِيدُ (Al-Majid)",
    "الْبَاعِثُ (Al-Ba'ith)",
    "الشَّهِيدُ (Ash-Shahid)",
    "الْحَقُ (Al-Haqq)",
    "الْوَكِيلُ (Al-Wakil)",
    "الْقَوِيُ (Al-Qawiyy)",
    "الْمَتِينُ (Al-Matin)",
    "الْوَلِيُّ (Al-Wali)",
    "ال ْحَمِيدُ (Al-Hamid)",
    "الْمُحْصِي (Al-Muhsi)",
    "الْمُبْتِي (Al-Mubdi)",
    "الْمُعِيدُ (Al-Mu'id)",
    "الْمُحْيِي (Al-Muhyi)",
    "الْمُمِيتُ (Al-Mumit)",
    "الْحَيُّ (Al-Hayy)",
    "الْقَيُّومُ (Al-Qayyum)",
    "الْوَاجِدُ (Al-W ajid)",
    "الْمَاجِدُ (Al-Majid)",
    "الْواحِدُ (Al-Wahid)",
    "الصَّمَدُ (As-Samad)",
    "الْقَادِرُ (Al-Qadir)",
    "الْمُقْتَدِرُ (Al-Muqtadir)",
    "الْمُقَدِّمُ (Al-Muqaddim)",
    "الْمُؤَخِّرُ (Al-Mu'akhkhir)",
    "الأوَّلُ (Al-Awwal)",
    "الْآخِرُ (Al-Akhir)",
    "الظَّاهِرُ (Az-Zahir)",
    "الْبَاطِنُ (Al-Batin)",
    "الْوَالِي (Al-Wali)",
    "الْمُتَعَالِي (Al-Muta'ali)",
    "الْبَرُّ (Al-Barr)",
    "الْتَّوَّابُ (At-Tawwab)",
    "الْمُنْتَقِمُ (Al-Muntaqim)",
    "الْعَفُوُّ (Al-Afuww)",
    "الرَّؤُوفُ (Ar-Ra'uf)",
    "مَالِكُ الْمُلْكِ (Malik-ul-Mulk)",
    "ذُو الْجَلَالِ وَالْإِكْرَامِ (Dhu-al-Jalali wa-al-Ikram)",
    "الْمُقْسِطُ (Al-Muqsit)",
    "الْجَامِعُ (Al-Jami)",
    "الْغَنِيُّ (Al-Ghani)",
    "الْمُغْنِي (Al-Mughni)",
    "الْمَانِعُ (Al-Mani)",
    "الْضَّارُ (Ad-Darr)",
    "النَّافِعُ (An-Nafi)",
    "النُّورُ (An-Nur)",
    "الْهَادِي (Al-Hadi)",
    "الْبَدِيعُ (Al-Badi)",
    "الْوَارِثُ (Al-Warith)",
    "الرَّشِيدُ (Ar-Rashid)",
    "الصَّبُورُ (As-Sabur)",
  ];

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('أسماء الله الحسنى',style: TextStyle(
          fontFamily: 'Tajawal',
          fontSize: 24,
          fontWeight: FontWeight.bold,
        ) ,),
      ),
      body: SingleChildScrollView(
        child: Padding(
          padding: const EdgeInsets.all(8.0),
          child: StaggeredGrid.count(
            crossAxisCount: 2,
            children: names.map((name) => Card(
              elevation: 4,
              shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.circular(10),
              ),
              child: Center(
                child: Padding(
                  padding: const EdgeInsets.all(16.0),
                  child: Text(
                    name,
                    textAlign: TextAlign.center,
                    style: const TextStyle(
                      fontFamily: 'Tajawal',
                      fontSize: 18,
                      fontWeight: FontWeight.bold,
                    ) ,
                  ),
                ),
              ),
            )).toList(),
          ),
        ),
      ),
    );
  }
}